on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    strategy:
      matrix:
        include:
          - buildName: Tether.exe
            os: windows
          - buildName: Tether.zip
            os: osx
          - buildName: Tether.x86_64
            os: linux
    steps:
      - uses: actions/checkout@v2.3.1
      - id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: ${{ matrix.buildName }}
          preset: ${{ matrix.os }}
          projectDir: ./
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          ITCH_USER: syc
          ITCH_GAME: tether
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.os }}
          PACKAGE: ${{ github.workspace }}/${{ steps.build.outputs.build }}
