on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    strategy:
      matrix:
        os: [windows, osx, linux]
    steps:
      - uses: actions/checkout@v1
      - id: godot
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: Tether
          preset: ${{ matrix.os }}
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          ITCH_USER: syc
          ITCH_GAME: tether
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.os }}
          PACKAGE: ${{ steps.godot.build }}
